// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/img.proto

package img

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_api_img_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_img_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_api_img_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type ImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageResponse) Reset() {
	*x = ImageResponse{}
	mi := &file_api_img_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResponse) ProtoMessage() {}

func (x *ImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_img_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResponse.ProtoReflect.Descriptor instead.
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return file_api_img_proto_rawDescGZIP(), []int{1}
}

func (x *ImageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_img_proto protoreflect.FileDescriptor

const file_api_img_proto_rawDesc = "" +
	"\n" +
	"\rapi/img.proto\x12\x03img\")\n" +
	"\fImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\"'\n" +
	"\rImageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2C\n" +
	"\fImageService\x123\n" +
	"\n" +
	"QueueImage\x12\x11.img.ImageRequest\x1a\x12.img.ImageResponseB\n" +
	"Z\b/api;imgb\x06proto3"

var (
	file_api_img_proto_rawDescOnce sync.Once
	file_api_img_proto_rawDescData []byte
)

func file_api_img_proto_rawDescGZIP() []byte {
	file_api_img_proto_rawDescOnce.Do(func() {
		file_api_img_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_img_proto_rawDesc), len(file_api_img_proto_rawDesc)))
	})
	return file_api_img_proto_rawDescData
}

var file_api_img_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_img_proto_goTypes = []any{
	(*ImageRequest)(nil),  // 0: img.ImageRequest
	(*ImageResponse)(nil), // 1: img.ImageResponse
}
var file_api_img_proto_depIdxs = []int32{
	0, // 0: img.ImageService.QueueImage:input_type -> img.ImageRequest
	1, // 1: img.ImageService.QueueImage:output_type -> img.ImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_img_proto_init() }
func file_api_img_proto_init() {
	if File_api_img_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_img_proto_rawDesc), len(file_api_img_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_img_proto_goTypes,
		DependencyIndexes: file_api_img_proto_depIdxs,
		MessageInfos:      file_api_img_proto_msgTypes,
	}.Build()
	File_api_img_proto = out.File
	file_api_img_proto_goTypes = nil
	file_api_img_proto_depIdxs = nil
}
